### ISSUE TITLE
insert mode mapping

### ISSUE THREAD

**Issue by liujoey** [rcmdnk/vim_emu#11]
Do you have plan to add some insert mode only mapping like Ctrl-w to delete word backward, Ctrl-u delete preceding line, etc.?

**Comment by rcmdnk** [comment]
Thanks for the comment.
These commands are useful, so I will try to include control commands in insert mode.

On the other hand, in Karabiner, there are "Emacs mode", and you can enable such 

    [ex] Control-W to Option+Delete

But such Control-U conflicts with vim_emu's Control-U at Normal mode (Emacs mode placed before vim_emu, then these option will override vim_emu's settings)
so, it seems actually better to have similar option in vim_emu.

**Comment by rcmdnk** [comment]
I implemented following keys:

|Key/Commands|Function|
|:----------:|:-------|
|Ctrl-c| Enter Normal mode.|
|Ctrl-i| Insert Tab.|
|Ctrl-j| Return.|
|Ctrl-m| Return.|
|Ctrl-t| Insert tab at the beginning of current line.|
|Ctrl-u| Cut the text between the beginning of the line and the current position.|
|Ctrl-w| Cut the word before the cursor.|

I also made a pull request to Karabiner, and it is already merged:
[Added additional Ctrl-X settings for vim_emu by rcmdnk · Pull Request #534 · tekezo/Karabiner](https://github.com/tekezo/Karabiner/pull/534#event-494504476)

so it will be available in Karabiner officially soon, too.
