### ISSUE TITLE
How do I disable vim complement mode ?

### ISSUE THREAD

**Issue by takanabe** [rcmdnk/vim_emu#12]
Hi ! 

I wanna disable `vim complement mode` (Ctrl + p, Ctrl + n) with vim_emu, but I could not.
Are there any ways to disable the mode?

**Comment by rcmdnk** [comment]
Thank you for the feedback.
Indeed, I understand this works sometime bad if people tend to use C-p/C-n for cursor moving.

Then, I separated this completion as another option.
I sent this update to Karabiner.
[Separated complement at insert mode for Vim Emulation by rcmdnk · Pull Request #577 · tekezo/Karabiner](https://github.com/tekezo/Karabiner/pull/577)

Once the update is done, the default setting is `vim complement mode` disabled.
To enable it, check `Enable Vim like complement`.

**Comment by takanabe** [comment]
Thank you for you quick response and I should have sent codes to implement same feature for Karabiner. 

Anyway, thank you and I will wait for the commit will be merged :)
