### ISSUE TITLE
How to use Hyper key to switch Visual Mode to Normal Mode in Vim Emulation feature

### ISSUE THREAD

**Issue by babygau** [rcmdnk/vim_emu#13]
Hi,

I am currently binding `CAPLOCKS` to `Hyper` key which is a combination of `CONTROL_L + OPTION_L + SHIFT_L + COMMAND_L`.

Let's say I'm on Visual Mode, in Karabiner, to escape Visual Mode, I can choose a number of ChangeKey such as `ChangeKey1` or `ChangeKey3` in which pressing `ESCAPE` will switch to Normal Mode. However, I want to emulate that behaviour with single press the `CAPLOCKS` key instead for more convenient. Let's think of `ChangeKey3` but with `Hyper` key. How could I do that?

Please find attached private.xml to see my current config. Any help would really appreciate!

[private.xml.txt](https://github.com/rcmdnk/vim_emu/files/130607/private.xml.txt)

**Comment by rcmdnk** [comment]
sorry for the late reply.
Though maybe you found anything to solve it,
I would help if possible.

First, I want to confirm that if the first `caps_lock_to_hyper` is correct or not.
I'm not familiar to CAPSLOCK in Karabiner, but I saw that CAPSLOCK is difficult to set in Karabiner
and normally it is recommended to use other application (https://pqrs.org/osx/karabiner/faq.html#capslock) or OSX's function if it is simple case. (like capslock to command)

To set ChangeKey, your private.xml is to use `Hyper` + `;`, right?
Is it working?
It seems correct way to add new ChangeKey.

If it is working but CapsLock doesn't work, I think it is the difficulty of CapsLock treatment in Karabiner.

**Comment by babygau** [comment]
@rcmdnk thank you for your response.

I haven't found a solution yet so I decided to leave it.

> First, I want to confirm that if the first caps_lock_to_hyper is correct or not

Yes, It is very common to use both `Karabiner` and `Seil`, I used `Seil` to set `Capslock` key to `F19`, and use `Karabiner` to set `F19` to `HYPER` key

> To set ChangeKey, your private.xml is to use Hyper + ;, right?

Yes, It's working for me. However, I just want to press `Capslock` only instead of reaching my finger to `;`. Sadly I couldn't replicate that behaviour.

**Comment by rcmdnk** [comment]
ok, I understand what you want to do.

Doesn't it work if you set ChangeKey1 (,2 or 3) which use `ESC` to enter Normal mode?

Karabiner nests key settings, so I think if you push only CapsLock (equals to F19), then it works as ESC, and then it works as `{{VIM_EMU_FORCE_OFF_ALL_BUT_LINE}}`.

**Comment by babygau** [comment]
@rcmdnk,

> Doesn't it work if you set ChangeKey1 (,2 or 3) which use ESC to enter Normal mode?

Nope, it's not working with my `Capslock` key, but `ESC` does. I thought `Capslock` = `ESC` but in this case, it's not. I toggled `Capslock` but nothing happened.

**Comment by rcmdnk** [comment]
hmm... maybe `__KeyOverlaidModifier__` is not so simple as I'm thinking.

Another possibility is to set F19 directly for vim_emu, like:

          <autogen> 
            __KeyOverlaidModifier__
            KeyCode::F19,
            KeyCode::COMMAND_L,
            ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L,
            {{VIM_EMU_FORCE_OFF_ALL_BUT_LINE}}
          </autogen>

for all places in `Customise Vim Emulation`.

Then place `caps_lock_to_hyper` after `Customise Vim Emulation`.

**Comment by babygau** [comment]
@rcmdnk, thank you for your suggesstion but I apparently can't get it worked. Do you mind correcting my mistake in case I did something wrong?

[private.xml.txt](https://github.com/rcmdnk/vim_emu/files/319775/private.xml.txt)

**Comment by rcmdnk** [comment]
In your new private.xml, hyperkey definition is like:

    ModifierFlag::COMMAND_L,  ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L,

but it should be 

    KeyCode::COMMAND_L,  ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L,

where the first one is `KeyCode`, instead of `ModifierFlag`.

I tried to change these options and use `F12` for the input key,
then it works.

**Comment by babygau** [comment]
@rcmdnk, 

Thank you so much, it worked 🎉

Now I could turn Vim Emulation on and off with just `HYPER` key, super convernient!

**Comment by rcmdnk** [comment]
glad to hear that :smile:
