### ISSUE TITLE
Is it possible to modify vim keybindings?

### ISSUE THREAD

**Issue by nikitavoloboev** [rcmdnk/vim_emu#14]
I would really like to map 'move to the end of line' which is right now '$' sign to '-' which is to the right of 0. It would really be great for me as I use it often.

Thank you and I hope this could be possible to do.

**Comment by rcmdnk** [comment]
Actually it is not easy to modify the key by private.xml.

For the temporary solution, you can modify

    /Applications/Karabiner.app/Contents/Resources/include/checkbox/vim_emu/vim_emu_move.xml

Around line 40, you can find 

     <autogen>
        __KeyToKey__ KeyCode::KEY_4,
        VK_SHIFT|ModifierFlag::NONE,
        {{VIM_EMU_BEFORE_MOVE}},
        KeyCode::CURSOR_RIGHT, {{VIM_EMU_USE_SHIFT}}VK_COMMAND,
        {{VIM_EMU_AFTER_MOVE}}
      </autogen>

Then, change second and third lines like:

        __KeyToKey__ KeyCode::MINUS,
         ModifierFlag::NONE,
