### ISSUE TITLE
I really wish there was zoom in and zoom out capability in the vim mode

### ISSUE THREAD

**Issue by nikitavoloboev** [rcmdnk/vim_emu#15]
There are extensions such as this : https://github.com/flipxfx/sVim
and this : https://github.com/1995eaton/chromium-vim

Which give vim keybindings for the browser. One of these bindings is zooming in and out of a page : 

![2016-05-28 at 11 54](https://cloud.githubusercontent.com/assets/6391776/15626670/36c84b7e-24cb-11e6-92d0-4adc20525695.png)

I find them to be incredibly useful and I wish vim_emu added support for them. 

Thank you and I hope you will consider adding it.

**Comment by rcmdnk** [comment]
Thank you for the suggestion.

I have implemented in this repository (not in Karabiner, yet).

If possible, could you please try it by:

- Replace **/Applications/Karabiner.app/Contents/Resources/include/checkbox/vim_emu/vim_emu_core_emu.xml** to [vim_emu_core_emu.xml](https://github.com/rcmdnk/vim_emu/blob/master/vim_emu/vim_emu_core_emu.xml). (maybe need Administrator's right)
- Reload XML in Karabiner.

It will give you commands `zi` (zoom in), `zo` (zoom out), and `z0` (zoom reset).
They are mapped to `Cmd`-`+`, `-` and `0`, respectively.

Note: It works such Preview.app well, while it does a bit different in TextEdit.app,
in which `Cmd`-`+`/`-` is assigned to making font large/small.
(View's large/small is `Shift`-`Cmd`-`,`/`.`.)

**Comment by nikitavoloboev** [comment]
Yep, that works perfectly. Thank you a lot, rcmdnk. ♥

**Comment by rcmdnk** [comment]
Thanks for the checking.
Then, I will make a pull request to Karabiner.

If you have more items which is useful for this, don't hesitate to make an issue.
(such vim add-ons are actually good example to think about other than original VIM command 😄 )
