### ISSUE TITLE
Reset vim_emu at Return in any case?

### ISSUE THREAD

**Issue by YayConnolly** [rcmdnk/vim_emu#16]
First of all thank you, I've really enjoyed starting to use vim bindings everywhere.

I often find myself editing a url. It would be great if vim_emu would go back to insert mode on hitting Return. Would it be possible to add an option like "Reset vim_emu at Return in any case"? Or can this be achieved by customizing karabiner's private.xml?

**Comment by rcmdnk** [comment]
The following code set RETURN to enter normal mode (Like ChangeKey1 for ESC).

If you want to use `RETURN`, you can use by holding RETURN key.

If you don't enable `Enable Vim like complement` then `<!-- Complement Mode-->` part is not necessary.
In addition, I think you don't need `<!-- Turn Off also IME if enabled -->` part.

    <item>
      <name>Return to normal mode</name>
      <identifier>remap.vim_emu_return_to_normal{{VIM_EMU_ALTCONFIG}}</identifier>
      <only>{{VIM_EMU_ONLY_APPS}}</only>
      <not>{{VIM_EMU_IGNORE_APPS}}</not>
      <block>
        <block> 
          <config_only>notsave.vim_emu_complement{{VIM_EMU_ALTCONFIG}}</config_only>
          <autogen>
            __HoldingKeyToKey__ KeyCode::RETURN,
            KeyCode::RETURN,
            KeyCode::VK_CONFIG_FORCE_OFF_notsave_vim_emu_complement{{VIM_EMU_ALTCONFIG}},
            KeyCode::VK_CONFIG_FORCE_ON_notsave_vim_emu_normal{{VIM_EMU_ALTCONFIG}},
            KeyCode::VK_NONE,
            KeyCode::RETURN, Option::NOREPEAT
          </autogen>
        </block>
        <block> 
          <config_only>notsave.vim_emu_search{{VIM_EMU_ALTCONFIG}}</config_only>
          <autogen>
            __HoldingKeyToKey__ KeyCode::RETURN,
            KeyCode::ESCAPE,
            KeyCode::VK_CONFIG_FORCE_OFF_notsave_vim_emu_search{{VIM_EMU_ALTCONFIG}},
            {{VIM_EMU_EMU_ON}}
            KeyCode::VK_CONFIG_FORCE_ON_notsave_vim_emu_normal{{VIM_EMU_ALTCONFIG}},
            KeyCode::VK_NONE,
            KeyCode::RETURN, Option::NOREPEAT
          </autogen>
        </block>
        <block> 
          <inputsource_only>JAPANESE</inputsource_only>
          <autogen>
            __HoldingKeyToKey__ KeyCode::RETURN,
            KeyCode::VK_CHANGE_INPUTSOURCE_ENGLISH,
            KeyCode::VK_CHANGE_INPUTSOURCE_JAPANESE,
            KeyCode::VK_CHANGE_INPUTSOURCE_ENGLISH,
            {{VIM_EMU_FORCE_ON_NORMAL_MODE}},
            KeyCode::VK_NONE,
            KeyCode::RETURN, Option::NOREPEAT
          </autogen>
        </block>
        
        <autogen>
          __HoldingKeyToKey__ {{VIM_EMU_CUSTOMIZE_KEY}},
          {{VIM_EMU_FORCE_ON_NORMAL_MODE}},
          KeyCode::VK_NONE,
          KeyCode::RETURN, Option::NOREPEAT
        </autogen>
      </block>
    </item>


By the way, I just made a pull request to Karabiner to enable customize keys for Vim Emulation.
Once it is implemented, you can use RETURN key to enter normal mode only by:

    <replacementdef>
      <replacementname>VIM_EMU_CUSTOMIZE_KEY</replacementname>
      <replacementvalue>KeyCode::RETURN</replacementvalue>
    </replacementdef>

and enable new setting of `ChaneKey13`.

I think it will be included in the beta version in a few days.

**Comment by YayConnolly** [comment]
(Sorry for the delayed reply, I responded earlier but must not have submitted it)

I tried the beta version of Karabiner and ChangeKey13, and it works to enter normal mode (vim emu on) with any custom key like return. But I was hoping for a way to enter insert mode (vim emu off) when pressing return. Is there a way to customize an arbitrary key (e.g. return, space, or tab) to enter insert mode (disable vim emu)?

**Comment by rcmdnk** [comment]
ah, sorry, I mistook it.

To set a key to change to the insert mode,
you can use following code in your private.xml:

    <item>
      <name>Return to insert mode</name
      <identifier>remap.vim_emu_return_to_insert{{VIM_EMU_ALTCONFIG}}</identifier>
      <only>{{VIM_EMU_ONLY_APPS}}</only>
      <not>{{VIM_EMU_IGNORE_APPS}}</not>
      <block>
        <config_only>notsave.vim_emu_normal{{VIM_EMU_ALTCONFIG}}</config_only>
        <autogen>
          __KeyToKey__ KeyCode::RETURN,
          {{VIM_EMU_NORMAL_OFF}}
        </autogen>
      </block>
    </item>

**Comment by YayConnolly** [comment]
Awesome, thank you! I wanted the "return" passed through, so I just had to add another event to the `__KeyToKey__` autogen:
```
<item>
    <name>Return to insert mode</name>
    <identifier>remap.vim_emu_return_to_insert{{VIM_EMU_ALTCONFIG}}</identifier>
    <only>{{VIM_EMU_ONLY_APPS}}</only>
    <not>{{VIM_EMU_IGNORE_APPS}}</not>
    <block>
      <config_only>notsave.vim_emu_normal{{VIM_EMU_ALTCONFIG}}</config_only>
      <autogen>
        __KeyToKey__ KeyCode::RETURN,
        {{VIM_EMU_NORMAL_OFF}},
        KeyCode::RETURN
      </autogen>
    </block>
  </item>
```
