### ISSUE TITLE
not able to enter visual mode

### ISSUE THREAD

**Issue by silverjam** [rcmdnk/vim_emu#17]
Hello,

While using vim emulation in Karabiner I'm not able to enter visual mode, if I press "V" or "v" while in normal mode, nothing happens.  Is this a configuration issue, or is something broken?

Thanks,
-Jason

**Comment by rcmdnk** [comment]
I'm using Karabiner 10.18.61 and it seems working.
Can you enter to normal mode at least?
When you enter the normal mode, you will see the popup of Karabiner with `-- VIM --`.
When `v` is push at the normal mode, the popup will change `-- VIM VISUAL --`.

**Comment by silverjam** [comment]
Yes, I can use normal mode, but I'm using 10.20.0 and I don't see the "--
VIM VISUAL--" notification (I do see the "-- VIM --" notification for
normal mode).

I can try to downgrade to 10.18.61 and see what happens.

**Comment by silverjam** [comment]
I downgraded to 10.18.0 (couldn't find 10.18.61 online) and I'm still not able to enter visual mode.  Any other ideas on how to debug this?  Thanks!

**Comment by rcmdnk** [comment]
10.18.61 is the beta version (can be upgraded from Karabiner)

[Karabiner Manual](https://pqrs.org/osx/karabiner/document.html)

But it should work with current version. These settings have not been changed.

Could you please check if you have any competitive settings in your private.xml or prior settings?
Maybe you can try to disable all but Vim Emulation, then see what will happen.
If it works there should be some settings on v.

**Comment by silverjam** [comment]
Hrmm, my private.xml is empty (it just has a root tag), and this is a new laptop that I just setup recently, so it shouldn't have any prior settings.

**Comment by rcmdnk** [comment]
Do you only enable Vim Emulation?
(Karabiner's settings->Change key and check show enabled only)

Another check is by enabling/disabling Disable all other non-assigned keys in other than Insert Mod
in Vim Emulation.

If this is not enabled, such t, which is not assigned to any functions, does just put t (please test on TextEdit, it is easy).
If it this option is enabled, nothing should happen.

When you push v by disabling this option, it should not show anything.
If it shows v, then v is already mapped to something and it puts v normally.

Maybe you can go Misc & Uninstall at Karabiner's settings,
Launch EventViewer and check your v.
