### ISSUE TITLE
about customization: <m>/<,> for page down/up and tab navigation

### ISSUE THREAD

**Issue by DiogoFerrari** [rcmdnk/vim_emu#18]
Fantastic application. To be perfect, there are just two modifications that I would like to have, but I don't know how to incorporate in your set up. First, I want to set <m> to be Page down, and <,> to be Page up. Second, I would like to have <Shift+h>,<Shift+j>, <Shift+k>, <Shift+l> to be, respectively, previous page (history back), left tab, right tab, and next page (history next) in chrome. Is it possible, and would you know how to do that?

**Comment by rcmdnk** [comment]
Here is an example of private.xml: [private.xml for Karabiner](https://gist.github.com/rcmdnk/60572fcb90efb8a8a96b6fac5045561c)

Currently I have only Sierra and I can't test Karabiner, so please try and let me know if it doesn't work.

**Comment by DiogoFerrari** [comment]
Yes, it works great. Thanks.
