### ISSUE TITLE
update for karabiner elements

### ISSUE THREAD

**Issue by nathanbraun** [rcmdnk/vim_emu#19]
Hi there, love this plugin -- it's seriously why I didn't want to upgrade my mac since karabiner doesn't work with the newest versions.  Are there any plans to make this work with karabiner-elements?

Cheers,
Nathan

**Comment by rcmdnk** [comment]
Yes, I made similar settings for Karabiner-Elements (sorry, I didn't give any information here. now added information in README.

Please go [Karabiner-Elements complex_modifications rules by rcmdnk](https://rcmdnk.com/KE-complex_modifications/) and import Vim Emulation from Karabiner-Elements.
It has almost all functions of vim_emu or more.

It is great if you use it and give me feedback if there is something not working compared with this vim_emu.

**Comment by nathanbraun** [comment]
Awesome!  Looks like it works great!  I have a minor issue, but I'll post it there.  Thanks again!
