### ISSUE TITLE
easier exit from VISUAL, c, d modes

### ISSUE THREAD

**Issue by nathanbraun** [rcmdnk/vim_emu#9]
Hi there, great plugin, still use everyday.

I use simultaneous 'jk' to toggle vim emulation on and off, however sometimes I find myself getting stuck in VIM VISUAL/c/d modes.  Is there anyway -- when in these modes -- that 'jk' could bring us back to regular VIM mode, similar to what escape currently does?

Thanks,
Nathan

**Comment by rcmdnk** [comment]
for now, it is not possible, sorry.
Karabiner can't work well if multi-functions are assigned to such "simultaneous" key in the different situation.
Therefore, curretly vim_emu assigns same "toggle" function to 'jk' for normal/insert mode.
and the function can't work in other modes.
(I tested with current one, but it seems still having a problem.)

Anyway, I will contact the author of Karabiner if it can be solved or not.

**Comment by rcmdnk** [comment]
Do you only enable Vim Emulation?
(Karabiner's settings->Change key and check `show enabled only`)

Another check is by enabling/disabling `Disable all other non-assigned keys in other than Insert Mod`
in Vim Emulation.

If this is not enabled, such `t`, which is not assigned to any functions, does just put `t` (please test on TextEdit, it is easy).
If it this option is enabled, nothing should happen.

When you push `v` by disabling this option, it should not show anything.
If it shows `v`, then `v` is already mapped to something and it puts `v` normally.

Maybe you can go Misc & Uninstall at Karabiner's settings,
`Launch EventViewer` and check your `v`.
